default: &default
  adapter: mysql2
  encoding: utf8
  database: autovid
  username: root
  password:
  host: 127.0.0.1
  port: 3306

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  database: autovid_test
