youtube_updater:
  cron: "*/5 * * * *"
  class: "YouTubeUpdateWorker"
  queue: default
video_purge:
  cron: "*/30 * * * *"
  class: "VideoPurgeWorker"
  queue: default
youtube_uploader:
  cron: "*/1 * * * *"
  class: "YouTubeUploader"
  queue: default
youtube_tagger:
  cron: "*/1 * * * *"
  class: "YouTubeTagger"
  queue: default
