---
# Follow the instructions at
# https://github.com/fullscreen/yt#configuring-your-app to set up your client
# id and secret. The refresh_tokens section should be populated by usernames
# and associated refresh tokens for each account you want to manage.
youtube:
  client_id: '198066865713-htjqm9nldba6cke00skja3udcj0f7tnn.apps.googleusercontent.com'
  client_secret: 'H9o5t8L4nMmzoAw3WiNAyEGV'
  refresh_tokens:
    CodeMonkeyPodcast: '1/ufiEuCgIJLKwnmKSOZbK5bqo7WH7bUIEZa7FfsR3iyc'
    placeholderTV: '1/m5JPupfq0CywCBVo9JtMfK1C7jPLMzue63yP2EkKdrI'
    gisikwReads: '1/R39gbGMfHDvx-I2XSTZFJvH0nVCi9wPaGjVJ5pvL0IQ'
    gisikwGames: '1/X5zR2JAmFacU0QvBGf_QotasmVYNGv28H2hejEgEA0k'
    gisikwVlogs: '1/W4TFkzCpIKjE1lhh68pfsI5ZORl5Ipj4aH6xrJpt72Q'
    gisikw: '1/7n8VCyfYlg1kMwXD_mddnvh2nrTvuXYBHEU6tPb9u-Q'
